FROM python:3

RUN mkdir /api
ADD /src/api /api
WORKDIR /api

ENV FLASK_APP=main.py
ENV FLASK_RUN_HOST=0.0.0.0

RUN apt-get update && apt-get upgrade -y && apt-get install -y
RUN pip install flask

EXPOSE 5000

CMD ["python","main.py"]
