version: '3.1'

services:

  supply-api:
    container_name: supply-api
    build: 
      context: ..
      dockerfile: docker/Dockerfile.api
    restart: always
    environment:
      - BACKEND_HOST=supply-api
    ports:
      - 5000:5000
    networks:
      - db_net

  webapp:
    container_name: webapp
    build:
      context: ..
      dockerfile: docker/Dockerfile.webapp
    restart: always
    environment:
      - HOST=supply-api
    ports:
      - 8000:8000
    networks:
      - db_net

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - /home/jonathan/dev/wvep/nginx/proxy.conf:/etc/nginx/conf.d/default.conf
    networks:
      - db_net

networks:
  db_net:
